### ISSUE TITLE
Sidebar fix and New XKit

### ISSUE THREAD

**Issue by invalidCards** [estufar/extensions#1]
Hey Estufar! 

I come on behalf of the [new XKit team](github.com/new-xkit), which is a team put together to revive and actively develop XKit once more. We were wondering whether you would like your sidebar fix, which until now had to be manually installed by each user in order to use it, to be added to the official XKit extension library by hosting it on [our fork of the XKit repo](github.com/new-xkit/XKit). 

If you have any questions, feel free to leave them here, and we're looking forward to your pull request!

**Comment by estufar** [comment]
Hi! Sorry I've taken so long to respond, I should really make sure my email notifications are on in GitHub. Yeah, I'll definitely add my sidebar fix to the extensions library. I'll probably be renaming it to something like "Old Sidebar" to have it fit in a bit better with the other extension names. It might take a little while before I end up making my pull request depending on what other things I have to do but I'll definitely do it soon!

**Comment by nightpool** [comment]
we can close this now :D
